# This template contains steps to build MsQuic for a single configuration.

parameters:
  image: ''
  container: ''
  platform: ''
  arch: ''
  tls: ''
  config: 'Debug,Release'
  extraPrepareArgs: ''
  extraBuildArgs: ''
  skipArtifacts: false
  extraName: ''
  ubuntuVersion: 20.04

jobs:
- job: build_${{ parameters.platform }}_${{ parameters.arch }}_${{ parameters.tls }}_${{ parameters.extraName }}
  displayName: ${{ parameters.arch }} ${{ parameters.tls }} ${{ parameters.extraName }}
  pool:
    vmImage: ${{ parameters.image }}
  ${{ if ne(parameters.container, '') }}:
    container: ${{ parameters.container }}
  steps:
  - checkout: self
    ${{ if eq(parameters.platform, 'windows') }}:
      path: msquic

  - pwsh: |
      Choco-Install -PackageName strawberryperl
      Write-Host "##vso[task.prependpath]C:\Strawberry\perl\bin"
    displayName: Install Perl
    condition: and(eq('${{ parameters.image }}', 'windows-2022'), eq('${{ parameters.tls }}', 'openssl'))

  - task: ShellScript@2
    displayName: Install Powershell
    condition: eq('${{ parameters.platform }}', 'linux')
    inputs:
      scriptPath: scripts/install-powershell.sh
      args: ${{ parameters.ubuntuVersion }}

  - task: PowerShell@2
    displayName: Prepare Build Machine
    inputs:
      pwsh: true
      filePath: scripts/prepare-machine.ps1
      arguments: -Tls ${{ parameters.tls }} -ForBuild ${{ parameters.extraPrepareArgs }}

  - script:
    - ${{ if and(succeeded(), contains('${{ parameters.config }}', 'Debug')) }}:
      - script: |
          unbuffer /usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command scripts/build.ps1 -Config Debug -Arch ${{ parameters.arch }} -Tls ${{ parameters.tls }} -Platform ${{ parameters.platform }} -CI ${{ parameters.extraBuildArgs }}

  - script:
    - ${{ if and(succeeded(), contains('${{ parameters.config }}', 'Release')) }}:
      - script: |
          unbuffer /usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command scripts/build.ps1 -Config Release -Arch ${{ parameters.arch }} -Tls ${{ parameters.tls }} -Platform ${{ parameters.platform }} -CI ${{ parameters.extraBuildArgs }}

  - ${{ if eq(parameters.skipArtifacts, false) }}:
    - template: ./upload-artifacts.yml
