################################################################################
#                  OneBranch Pipelines - Official                              #
################################################################################
#                                                                              #
# This pipeline is for validation of official commits. Useful links:           #
#                                                                              #
#   https://www.osgwiki.com/wiki/Windows_Undocked_Template                     #
#   https://aka.ms/obpipelines                                                 #
#   https://aka.ms/obpipelines/yaml/schema                                     #
#   https://aka.ms/obpipelines/tasks                                           #
#   https://aka.ms/onebranchsup                                                #
#                                                                              #
################################################################################

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - msrc/*
  tags:
    include:
    - v*

# Package and ingestion are disabled by default.
# Manual runs on the main pipeline are required for packaging/ingestion.
parameters:
- name: ingest
  type: boolean
  displayName: Create VPack & Ingest
  default: false
- name: branch
  type: string
  displayName: OS branch to ingest to
  default: official/rs_onecore_liof1_stack
- name: 'WindowsContainerImage2DockerTag'
  displayName: 'WindowsContainerImage2 DockerTag'
  type: string
  default: 'vse2022.5'

variables:
  DisableDockerDetector: true
  ONEBRANCH_AME_ACR_LOGIN: onebranch.azurecr.io, cdpxb7b51c2f738e43e48f7605d9a8e5f6d700.azurecr.io
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest'
  WindowsContainerImage2: 'cdpxb7b51c2f738e43e48f7605d9a8e5f6d700.azurecr.io/b7b51c2f-738e-43e4-8f76-05d9a8e5f6d7/official/msquicbuild:${{ parameters.WindowsContainerImage2DockerTag }}'
  LinuxContainerImage: 'ghcr.io/microsoft/msquic/linux-build-xcomp:22.04'
  LinuxContainerImage2: 'ghcr.io/microsoft/msquic/linux-build-xcomp:20.04'

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    cloudvault: # https://aka.ms/obpipelines/cloudvault
      enabled: false
    globalSdl: # https://aka.ms/obpipelines/sdl
      # Disable TSA to force build breaks instead of bugs.
      tsa:
        enabled: false
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.azure\CredScanSuppressions.json
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\.azure\openssl.gdnsuppress
    featureFlags:
      linuxEsrpSigningPreview: true
      WindowsHostVersion: '1ESWindows2022'

    stages:
    - stage: build_winkernel
      displayName: Build Windows Kernel
      dependsOn: []
      jobs:
      - template: .azure/obtemplates/build-winkernel.yml@self
        parameters:
          config: Release
      - template: .azure/obtemplates/build-winkernel.yml@self
        parameters:
          config: Debug

    - stage: build_windows_xdp
      displayName: Build Windows XDP
      dependsOn: []
      jobs:
      - template: .azure/obtemplates/build-winuser-xdp.yml@self
        parameters:
          config: Release
          tls: schannel
      - template: .azure/obtemplates/build-winuser-xdp.yml@self
        parameters:
          config: Release
          tls: openssl
      - template: .azure/obtemplates/build-winuser-xdp.yml@self
        parameters:
          config: Debug

    - stage: build_windows
      displayName: Build Windows
      dependsOn: []
      jobs:
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Release
          tls: schannel
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Debug
          tls: schannel
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Release
          tls: openssl
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Debug
          tls: openssl
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Release
          tls: openssl3
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Debug
          tls: openssl3

    - stage: build_gamecore_console
      displayName: Build Gamecore
      dependsOn: []
      jobs:
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Release
          tls: schannel
          platform: gamecore_console
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Debug
          tls: schannel
          platform: gamecore_console

    - stage: build_uwp
      displayName: Build Windows UWP
      dependsOn: []
      jobs:
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Release
          tls: schannel
          platform: uwp
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Debug
          tls: schannel
          platform: uwp
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Release
          tls: openssl
          platform: uwp
      - template: .azure/obtemplates/build-winuser.yml@self
        parameters:
          config: Debug
          tls: openssl
          platform: uwp

    - stage: build_linux
      displayName: Build Linux
      dependsOn: []
      jobs:
      - template: .azure/obtemplates/build-linux.yml@self
        parameters:
          config: Release
      - template: .azure/obtemplates/build-linux.yml@self
        parameters:
          config: Debug
      - template: .azure/obtemplates/build-linux.yml@self
        parameters:
          config: Release
          tls: openssl3
      - template: .azure/obtemplates/build-linux.yml@self
        parameters:
          config: Debug
          tls: openssl3

    - stage: package_linux
      displayName: Package Linux
      dependsOn:
      - build_linux
      jobs:
      - template: .azure/obtemplates/build-linux-packages.yml@self
        parameters:
          sign: true

    - stage: package_windows
      displayName: Package Windows
      dependsOn:
      - build_windows
      - build_uwp
      - build_windows_xdp
      jobs:
      - template: .azure/obtemplates/build-nuget.yml@self
        ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
          parameters:
            release: true
